sonar.projectKey=queueguard
sonar.projectName=QueueGuard
sonar.sources=queue_service/app,booking_service/app,notification_service/app
sonar.tests=queue_service/tests,booking_service/tests,notification_service/tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=queue_service/coverage.xml,booking_service/coverage.xml,notification_service/coverage.xml
sonar.exclusions=**/.venv/**,**/__pycache__/**
